// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oauth2_client_socket.proto

#include "oauth2_client_socket.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace oauth2ClientSocket {

inline constexpr SocketIdWithToken::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : accesstoken_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        refreshtoken_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        socketid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SocketIdWithToken::SocketIdWithToken(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SocketIdWithTokenDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SocketIdWithTokenDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SocketIdWithTokenDefaultTypeInternal() {}
  union {
    SocketIdWithToken _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SocketIdWithTokenDefaultTypeInternal _SocketIdWithToken_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR Empty::Empty(::_pbi::ConstantInitialized) {}
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;
}  // namespace oauth2ClientSocket
static ::_pb::Metadata file_level_metadata_oauth2_5fclient_5fsocket_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_oauth2_5fclient_5fsocket_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_oauth2_5fclient_5fsocket_2eproto = nullptr;
const ::uint32_t TableStruct_oauth2_5fclient_5fsocket_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::oauth2ClientSocket::SocketIdWithToken, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::oauth2ClientSocket::SocketIdWithToken, _impl_.socketid_),
    PROTOBUF_FIELD_OFFSET(::oauth2ClientSocket::SocketIdWithToken, _impl_.accesstoken_),
    PROTOBUF_FIELD_OFFSET(::oauth2ClientSocket::SocketIdWithToken, _impl_.refreshtoken_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::oauth2ClientSocket::Empty, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::oauth2ClientSocket::SocketIdWithToken)},
        {11, -1, -1, sizeof(::oauth2ClientSocket::Empty)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::oauth2ClientSocket::_SocketIdWithToken_default_instance_._instance,
    &::oauth2ClientSocket::_Empty_default_instance_._instance,
};
const char descriptor_table_protodef_oauth2_5fclient_5fsocket_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\032oauth2_client_socket.proto\022\022oauth2Clie"
    "ntSocket\"P\n\021SocketIdWithToken\022\020\n\010socketI"
    "d\030\001 \001(\005\022\023\n\013accessToken\030\002 \001(\t\022\024\n\014refreshT"
    "oken\030\003 \001(\t\"\007\n\005Empty2m\n\022OAuth2ClientSocke"
    "t\022W\n\021SendTokenAndClose\022%.oauth2ClientSoc"
    "ket.SocketIdWithToken\032\031.oauth2ClientSock"
    "et.Empty\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_oauth2_5fclient_5fsocket_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_oauth2_5fclient_5fsocket_2eproto = {
    false,
    false,
    258,
    descriptor_table_protodef_oauth2_5fclient_5fsocket_2eproto,
    "oauth2_client_socket.proto",
    &descriptor_table_oauth2_5fclient_5fsocket_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_oauth2_5fclient_5fsocket_2eproto::offsets,
    file_level_metadata_oauth2_5fclient_5fsocket_2eproto,
    file_level_enum_descriptors_oauth2_5fclient_5fsocket_2eproto,
    file_level_service_descriptors_oauth2_5fclient_5fsocket_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_oauth2_5fclient_5fsocket_2eproto_getter() {
  return &descriptor_table_oauth2_5fclient_5fsocket_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_oauth2_5fclient_5fsocket_2eproto(&descriptor_table_oauth2_5fclient_5fsocket_2eproto);
namespace oauth2ClientSocket {
// ===================================================================

class SocketIdWithToken::_Internal {
 public:
};

SocketIdWithToken::SocketIdWithToken(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:oauth2ClientSocket.SocketIdWithToken)
}
inline PROTOBUF_NDEBUG_INLINE SocketIdWithToken::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : accesstoken_(arena, from.accesstoken_),
        refreshtoken_(arena, from.refreshtoken_),
        _cached_size_{0} {}

SocketIdWithToken::SocketIdWithToken(
    ::google::protobuf::Arena* arena,
    const SocketIdWithToken& from)
    : ::google::protobuf::Message(arena) {
  SocketIdWithToken* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.socketid_ = from._impl_.socketid_;

  // @@protoc_insertion_point(copy_constructor:oauth2ClientSocket.SocketIdWithToken)
}
inline PROTOBUF_NDEBUG_INLINE SocketIdWithToken::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : accesstoken_(arena),
        refreshtoken_(arena),
        _cached_size_{0} {}

inline void SocketIdWithToken::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.socketid_ = {};
}
SocketIdWithToken::~SocketIdWithToken() {
  // @@protoc_insertion_point(destructor:oauth2ClientSocket.SocketIdWithToken)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SocketIdWithToken::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.accesstoken_.Destroy();
  _impl_.refreshtoken_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void SocketIdWithToken::Clear() {
// @@protoc_insertion_point(message_clear_start:oauth2ClientSocket.SocketIdWithToken)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.accesstoken_.ClearToEmpty();
  _impl_.refreshtoken_.ClearToEmpty();
  _impl_.socketid_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* SocketIdWithToken::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 68, 2> SocketIdWithToken::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SocketIdWithToken_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 socketId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SocketIdWithToken, _impl_.socketid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SocketIdWithToken, _impl_.socketid_)}},
    // string accessToken = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SocketIdWithToken, _impl_.accesstoken_)}},
    // string refreshToken = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(SocketIdWithToken, _impl_.refreshtoken_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 socketId = 1;
    {PROTOBUF_FIELD_OFFSET(SocketIdWithToken, _impl_.socketid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string accessToken = 2;
    {PROTOBUF_FIELD_OFFSET(SocketIdWithToken, _impl_.accesstoken_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string refreshToken = 3;
    {PROTOBUF_FIELD_OFFSET(SocketIdWithToken, _impl_.refreshtoken_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\44\0\13\14\0\0\0\0"
    "oauth2ClientSocket.SocketIdWithToken"
    "accessToken"
    "refreshToken"
  }},
};

::uint8_t* SocketIdWithToken::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:oauth2ClientSocket.SocketIdWithToken)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 socketId = 1;
  if (this->_internal_socketid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_socketid(), target);
  }

  // string accessToken = 2;
  if (!this->_internal_accesstoken().empty()) {
    const std::string& _s = this->_internal_accesstoken();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "oauth2ClientSocket.SocketIdWithToken.accessToken");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string refreshToken = 3;
  if (!this->_internal_refreshtoken().empty()) {
    const std::string& _s = this->_internal_refreshtoken();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "oauth2ClientSocket.SocketIdWithToken.refreshToken");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:oauth2ClientSocket.SocketIdWithToken)
  return target;
}

::size_t SocketIdWithToken::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:oauth2ClientSocket.SocketIdWithToken)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string accessToken = 2;
  if (!this->_internal_accesstoken().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_accesstoken());
  }

  // string refreshToken = 3;
  if (!this->_internal_refreshtoken().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_refreshtoken());
  }

  // int32 socketId = 1;
  if (this->_internal_socketid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_socketid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData SocketIdWithToken::_class_data_ = {
    SocketIdWithToken::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* SocketIdWithToken::GetClassData() const {
  return &_class_data_;
}

void SocketIdWithToken::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<SocketIdWithToken*>(&to_msg);
  auto& from = static_cast<const SocketIdWithToken&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:oauth2ClientSocket.SocketIdWithToken)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_accesstoken().empty()) {
    _this->_internal_set_accesstoken(from._internal_accesstoken());
  }
  if (!from._internal_refreshtoken().empty()) {
    _this->_internal_set_refreshtoken(from._internal_refreshtoken());
  }
  if (from._internal_socketid() != 0) {
    _this->_internal_set_socketid(from._internal_socketid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SocketIdWithToken::CopyFrom(const SocketIdWithToken& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:oauth2ClientSocket.SocketIdWithToken)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SocketIdWithToken::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* SocketIdWithToken::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void SocketIdWithToken::InternalSwap(SocketIdWithToken* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.accesstoken_, &other->_impl_.accesstoken_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.refreshtoken_, &other->_impl_.refreshtoken_, arena);
        swap(_impl_.socketid_, other->_impl_.socketid_);
}

::google::protobuf::Metadata SocketIdWithToken::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_oauth2_5fclient_5fsocket_2eproto_getter, &descriptor_table_oauth2_5fclient_5fsocket_2eproto_once,
      file_level_metadata_oauth2_5fclient_5fsocket_2eproto[0]);
}
// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:oauth2ClientSocket.Empty)
}
Empty::Empty(
    ::google::protobuf::Arena* arena,
    const Empty& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  Empty* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:oauth2ClientSocket.Empty)
}









::google::protobuf::Metadata Empty::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_oauth2_5fclient_5fsocket_2eproto_getter, &descriptor_table_oauth2_5fclient_5fsocket_2eproto_once,
      file_level_metadata_oauth2_5fclient_5fsocket_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace oauth2ClientSocket
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
